name: Fdroid version file generation

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-[0-9]+'

jobs:
  # https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.carriez.flutter_hbb.yml
  # Finds latest release and transforms F-Droid vereion code from version as follows:
  # X.Y.Z-A => X * 1e9 + Y * 1e6 + Z * 1e3 + A
  update-fdroid-version-file:
    name: Publish SASHRDesk version file for F-Droid updater
    runs-on: ubuntu-latest
    steps:
      - name: Generate SASHRDesk version file
        run: |
          UPSTREAM_VERNAME="$(curl https://api.github.com/repos/rustdesk/rustdesk/releases/latest  | jq -r .tag_name | sed 's/^v//')"
          UPSTREAM_VERCODE="$(echo "$UPSTREAM_VERNAME" | tr '.' ' ' | tr '-' ' ' | while read -r MAJOR MINOR PATCH REV; do [ -z "$MAJOR" ] && MAJOR=0; [ -z "$MINOR" ] && MINOR=0; [ -z "$PATCH" ] && PATCH=0; [ -z "$REV" ] && REV=0; echo "$(( 1000000000 * $MAJOR + 1000000 * $MINOR + 1000 * $PATCH + $REV ))"; done)"
          echo "versionName=$UPSTREAM_VERNAME"  > sashrdesk-version.txt
          echo "versionCode=$UPSTREAM_VERCODE" >> sashrdesk-version.txt
        shell: bash

      - name: Publish SASHRDesk version file
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          tag_name: "fdroid-version"
          files: |
            ./sashrdesk-version.txt
